# 
# This version SpigotBuildAction script is outdated.
# Use "BuildSpigot with Latest BuildTools" in "~/.github/workflows/buildspigot-buildtools.yml".
# No further support on this script.
# 
name: BuildSpigot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get BuildTools from repo
      - name: Getting BuildTools
        uses: actions/checkout@v2

      # Build Spigot by BuildTools
      - name: Building Spigot
        # !! Change 'latest' to the version what you wanted. !!
        run: java -jar BuildTools.jar --rev latest
      
      # Uploading the build jar files.
      - name: Uploading Build
        uses: actions/upload-artifact@v4
        with:
          name: spigot
          path: ./spigot*.jar
      
